/** openbrain-memory-ts: contract peer of `python/openbrain-memory`. */

export {
  COMPATIBLE_CONTRACT_VERSIONS,
  CURRENT_CONTRACT_HEADER,
  CURRENT_CONTRACT_SCHEMA_HASH,
  CURRENT_CONTRACT_SCHEMA_VERSION,
  CURRENT_CONTRACT_VERSION,
  EXPECTED_CONTRACT_SCOPE,
  FIRST_CLASS_RUNTIME_TOOLS,
  FIRST_CLASS_RUNTIME_TOOL_VERSIONS,
  validateContractManifest,
  validateFirstClassContract,
  type ContractValidationResult,
} from "./contract.ts";
export {
  FetchTransport,
  OpenBrainClient,
  OpenBrainError,
  OpenBrainHTTPError,
  OpenBrainProtocolError,
  OpenBrainToolError,
  MCP_PROTOCOL_VERSION,
  type Json,
  type OpenBrainClientOptions,
  type Transport,
  type TransportResponse,
} from "./client.ts";
export {
  HEURISTIC_REDACTION_PATTERNS,
  SECRET_PATTERNS,
  SENSITIVE_KEY_RE,
  ValidationError,
  idempotencyKey,
  redactText,
  redactValue,
  rejectSecretPayload,
} from "./policy.ts";
export {
  DEFAULT_QUARANTINE_THRESHOLD,
  JsonlSpool,
  QUARANTINE_ENVELOPE_SCHEMA,
  RETRY_STATE_SCHEMA,
  SpoolFullError,
  SpoolUnitRetained,
  errorClassName,
  fileMode,
  type SpoolAppendRecord,
  type SpoolDispatcher,
  type SpoolRecord,
  type SpoolReplayReport,
  type SpoolStatus,
  type SpoolUnitOutcome,
} from "./spool.ts";
export {
  CONTEXT_PACK_SECTIONS,
  DrainReport,
  EVENT_TYPES,
  FirstClassMemoryRuntime,
  PARKED_NAMESPACE_KEY,
  REPLAYABLE_SPOOL_OPERATIONS,
  RUNTIME_RECEIPT_SCHEMA,
  ReceiptStatus,
  RuntimeCallError,
  RuntimeReceipt,
  RuntimeScope,
  ScopeProofError,
  safeError,
  safeText,
  type DirectClient,
  type FirstClassMemoryRuntimeOptions,
  type MemorySpoolLike,
  type ReceiptStatusValue,
  type RuntimeConfig,
  type RuntimeOutput,
  type RuntimeReceiptInit,
} from "./runtime.ts";
export {
  PUBLIC_ERROR_CATEGORIES,
  PUBLIC_ERROR_STATUSES,
  PUBLIC_RECEIPT_SCHEMA,
  coerceErrorCategory,
  errorCategory,
  publicReceipt,
  type PublicErrorCategory,
  type PublicReceipt,
} from "./receipts.ts";
export {
  MAX_DISTILLED_CONTENT_BYTES,
  distilledContent,
  exactScopeFields,
  persistedText,
  validateContextPackScope,
  validateExactFields,
  validateStartedLane,
  type RuntimeScopeCoordinates,
} from "./validation.ts";
