"""Public API for the Open Brain memory client package."""

from __future__ import annotations

from .agent import (
    AgentMemory,
    MemoryClient,
    MemoryContext,
    MemoryItem,
    MemoryPolicy,
    MemorySpool,
)
from .client import (
    COMPATIBLE_CONTRACT_VERSIONS,
    CURRENT_CONTRACT_HEADER,
    CURRENT_CONTRACT_SCHEMA_HASH,
    CURRENT_CONTRACT_SCHEMA_VERSION,
    CURRENT_CONTRACT_VERSION,
    CURRENT_TOOL_HELP,
    DEFAULT_NATS_CONTEXT_PACK_SUBJECT,
    DEFAULT_NATS_ENV,
    PACKAGE_VERSION,
    REQUIRED_CONTRACT_TOOLS,
    FleetNatsDriver,
    NatsRequestReplyDriver,
    NatsTransport,
    OpenBrainClient,
    OpenBrainError,
    OpenBrainHTTPError,
    OpenBrainProtocolError,
    OpenBrainToolError,
    OpenBrainTransportUnavailableError,
    RealtimeTransportAvailability,
)
from .contract import (
    ContractValidationResult,
    validate_contract_manifest,
    validate_required_memory_contract,
)
from .dream import DreamAction, DreamClient, DreamEngine, DreamPolicy, DreamRun
from .maintenance import (
    SPOOL_REPLAY_JOB_KIND,
    MaintenanceHandler,
    MaintenanceRegistry,
    MaintenanceRegistryError,
    MaintenanceScheduler,
    SpoolReplayMaintenanceHandler,
)
from .policy import RetryExhaustedError, RetryPolicy, redact_text, redact_value
from .runtime import (
    DrainReport,
    FirstClassMemoryRuntime,
    ReceiptStatus,
    RuntimeConfig,
    RuntimeOutput,
    RuntimeReceipt,
    RuntimeScope,
)
from .schema import (
    ContractSchemaError,
    contract_field_to_json_schema,
    contract_input_to_json_schema,
    tool_contract_to_input_schema,
    tool_contracts_to_tool_schemas,
)
from .spool import (
    JsonlSpool,
    SpoolRecord,
    SpoolReplayReport,
    SpoolStatus,
    SpoolUnitOutcome,
    SpoolUnitRetained,
    replay_records,
)
from .turn_concepts import (
    DEFAULT_MAX_KEYS,
    TurnConcepts,
    extract_turn_concepts,
)

__all__ = [
    "AgentMemory",
    "DEFAULT_MAX_KEYS",
    "TurnConcepts",
    "extract_turn_concepts",
    "DreamAction",
    "DreamClient",
    "DreamEngine",
    "DreamPolicy",
    "DreamRun",
    "MaintenanceHandler",
    "MaintenanceRegistry",
    "MaintenanceRegistryError",
    "MaintenanceScheduler",
    "MemoryClient",
    "MemoryContext",
    "MemoryItem",
    "MemoryPolicy",
    "MemorySpool",
    "OpenBrainClient",
    "OpenBrainError",
    "OpenBrainHTTPError",
    "OpenBrainProtocolError",
    "OpenBrainToolError",
    "PACKAGE_VERSION",
    "COMPATIBLE_CONTRACT_VERSIONS",
    "CURRENT_CONTRACT_HEADER",
    "CURRENT_CONTRACT_SCHEMA_HASH",
    "CURRENT_CONTRACT_SCHEMA_VERSION",
    "CURRENT_CONTRACT_VERSION",
    "CURRENT_TOOL_HELP",
    "DEFAULT_NATS_CONTEXT_PACK_SUBJECT",
    "DEFAULT_NATS_ENV",
    "REQUIRED_CONTRACT_TOOLS",
    "ContractValidationResult",
    "ContractSchemaError",
    "DrainReport",
    "FirstClassMemoryRuntime",
    "FleetNatsDriver",
    "JsonlSpool",
    "NatsRequestReplyDriver",
    "NatsTransport",
    "ReceiptStatus",
    "RetryExhaustedError",
    "RetryPolicy",
    "RealtimeTransportAvailability",
    "RuntimeConfig",
    "RuntimeOutput",
    "RuntimeReceipt",
    "RuntimeScope",
    "SPOOL_REPLAY_JOB_KIND",
    "SpoolReplayMaintenanceHandler",
    "SpoolRecord",
    "SpoolReplayReport",
    "SpoolStatus",
    "SpoolUnitOutcome",
    "SpoolUnitRetained",
    "contract_field_to_json_schema",
    "contract_input_to_json_schema",
    "OpenBrainTransportUnavailableError",
    "redact_text",
    "redact_value",
    "replay_records",
    "tool_contract_to_input_schema",
    "tool_contracts_to_tool_schemas",
    "validate_contract_manifest",
    "validate_required_memory_contract",
]
