/**
 * Mirror every issue in this repo into _plans/issues/ as searchable markdown.
 *
 * WHY. Issue bodies live on the forge. Nothing in this working tree can search
 * them, diff them, or recover them when a session drops -- so the same design
 * questions get re-asked: what was the original goal, did we already plan that,
 * did we make this once? Operator, 2026-07-28: "we keep a copy of all issues
 * that are created ... so we don't have to keep trying to remember what was the
 * original goal."
 *
 * COMMENTS ARE THE POINT, NOT THE BODY. The opening body says what someone
 * thought at the time; the comments carry the corrections that reshaped it.
 * #390's body describes the Light stage, but the reasoning that made it
 * model-free is in a comment. A mirror without comments would miss exactly the
 * material this exists to preserve.
 *
 * EVERYTHING IS INDEXED, NO TRIAGE. Operator decision, 2026-07-28: index all of
 * them rather than classifying substantive-vs-side-quest first. Triage by title
 * misjudges -- a chore-sounding title can hide the reasoning for a whole class
 * of bug -- and a misfiled issue is invisible, which is the failure this is
 * meant to fix. Noisier search beats lost context.
 *
 * THESE FILES ARE GENERATED. They are overwritten on every run, so hand edits
 * are lost. Authored thinking goes in _plans/<n>-<slug>.md, which this never
 * touches. The header in each generated file says so.
 *
 * Going forward the markdown comes FIRST: write _plans/<slug>.md, and that is
 * what becomes the issue body. This script then backfills the discussion.
 */

const OUT_DIR = "_plans/issues";

type Issue = {
  number: number;
  title: string;
  state: string;
  createdAt: string;
  updatedAt: string;
  closedAt: string | null;
  author: { login: string } | null;
  labels: { name: string }[];
  milestone: { title: string } | null;
  body: string;
  comments: {
    author: { login: string } | null;
    createdAt: string;
    body: string;
  }[];
};

/** Filesystem-safe, stable, and readable in a search hit. */
function slug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
}

function render(i: Issue): string {
  const labels = i.labels.map((l) => l.name).join(", ") || "none";
  const closed = i.closedAt ? `\nClosed: ${i.closedAt}` : "";
  const milestone = i.milestone ? `\nMilestone: ${i.milestone.title}` : "";

  const head = `<!-- GENERATED by scripts/sync-issues.ts. Do not edit: this file is
     overwritten on every sync. Authored plans live in _plans/<n>-<slug>.md. -->

# #${i.number} — ${i.title}

State: ${i.state}
Author: ${i.author?.login ?? "unknown"}
Labels: ${labels}
Created: ${i.createdAt}
Updated: ${i.updatedAt}${closed}${milestone}

---

${i.body?.trim() || "_(no body)_"}
`;

  if (!i.comments.length) return head;

  // Comments in chronological order: a correction only makes sense after the
  // thing it corrects.
  const thread = i.comments
    .map(
      (c) =>
        `### ${c.author?.login ?? "unknown"} — ${c.createdAt}\n\n${c.body.trim()}`,
    )
    .join("\n\n---\n\n");

  return `${head}\n---\n\n## Discussion (${i.comments.length})\n\n${thread}\n`;
}

const proc = Bun.spawn(
  [
    "gh",
    "issue",
    "list",
    "--state",
    "all",
    "--limit",
    "1000",
    "--json",
    "number,title,state,createdAt,updatedAt,closedAt,author,labels,milestone,body,comments",
  ],
  { stdout: "pipe", stderr: "pipe" },
);

const raw = await new Response(proc.stdout).text();
const exit = await proc.exited;
if (exit !== 0) {
  console.error(await new Response(proc.stderr).text());
  process.exit(1);
}

const issues: Issue[] = JSON.parse(raw);
issues.sort((a, b) => a.number - b.number);

// A retitled issue would otherwise leave its old file behind as a stale
// duplicate that still answers searches. Keep exactly one file per number.
const keep = new Set(issues.map((i) => `${i.number}-${slug(i.title)}.md`));
const existing = new Bun.Glob("*.md").scanSync({
  cwd: OUT_DIR,
  onlyFiles: true,
});
let stale = 0;
for (const f of existing) {
  if (!keep.has(f)) {
    await Bun.file(`${OUT_DIR}/${f}`).delete();
    stale++;
  }
}

let comments = 0;
for (const i of issues) {
  comments += i.comments.length;
  await Bun.write(`${OUT_DIR}/${i.number}-${slug(i.title)}.md`, render(i));
}

const open = issues.filter((i) => i.state === "OPEN").length;
console.log(
  `${issues.length} issues (${open} open, ${issues.length - open} closed), ` +
    `${comments} comments -> ${OUT_DIR}/` +
    (stale ? `, removed ${stale} stale` : ""),
);
console.log(
  "Run `qmd sync` (or the repo's index refresh) to make these searchable.",
);
